version: '3.8'

# Define a project name explicitly to prevent folder influence
name: dms_project

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Publicly expose port 80 for the frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount NGINX configuration
    depends_on:
      - web-app
      - web-api
    networks:
      - dms_network
    restart: unless-stopped

  web-app:
    image: dms_project-web-app
    container_name: web-app
    build:
      context: .
      dockerfile: WebUI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3000  # Ensure the app binds to all interfaces on port 3000
    expose:
      - "3000"  # Expose port 3000 for internal Docker network communication
    depends_on:
      - postgres
    networks:
      - dms_network
    restart: unless-stopped

  web-api:
    image: dms_project-web-api
    container_name: web-api
    build:
      context: .
      dockerfile: DMSystem/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    volumes:
      - shared-config:/app/config  # Use shared volume for appsettings.json
      - ./DMSystem/log4net.config:/app/log4net.config
      - ./DMSystem/Logs:/app/Logs
    expose:
      - "5000"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - dms_network
    restart: unless-stopped

  ocr-worker:
    image: dms_project-ocr-worker
    container_name: ocr-worker
    build:
      context: .
      dockerfile: DMSystem.OCRWorker/Dockerfile
    environment:
      - TESSDATA_PREFIX=/app/tessdata
      - OCR_PDF_STORAGE=/data/pdf_storage
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=groupb
      - MINIO_SECRET_KEY=testtest
      - MINIO_BUCKET_NAME=pdf-storage
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - shared-config:/app/config  # Use shared volume for appsettings.json
      - ./pdf_storage:/data/pdf_storage  # Mount volume for PDF storage
      - ./DMSystem.OCRWorker/tessdata:/app/tessdata  # Ensure tessdata is available
    depends_on:
      - rabbitmq
      - web-api
      - postgres
      - minio
      - elasticsearch
    networks:
      - dms_network
    restart: unless-stopped

  elasticsearch-indexer:
    image: dms_project-elasticsearch-indexer
    container_name: elasticsearch-indexer
    build:
      context: .
      dockerfile: DMSystem.Elasticsearch/Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=groupb
      - RABBITMQ_PASSWORD=testtest
      - RABBITMQ_QUEUE=ocrResultsQueue
    depends_on:
      - rabbitmq
      - elasticsearch
    networks:
      - dms_network
    restart: unless-stopped

  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    environment:
      POSTGRES_USER: groupb
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: dm_system
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres  # Persist database data
    expose:
      - "5432"  # Expose PostgreSQL port internally
    networks:
      - dms_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: groupb
      RABBITMQ_DEFAULT_PASS: testtest
    ports:
      - "8081:15672"  # Management UI port
      - "5672:5672"   # AMQP port for application
    networks:
      - dms_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"  # Expose pgAdmin web interface
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - dms_network
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: groupb
      MINIO_ROOT_PASSWORD: testtest
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - dms_network
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for development
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Set Java heap size
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # Elasticsearch API
    networks:
      - dms_network
    restart: unless-stopped

networks:
  dms_network:
    name: dms_network
    driver: bridge

volumes:
  shared-config:  # Shared volume for appsettings.json
  postgres:
  pgadmin:
  pdf_storage:
  minio_data:  # Volume for MinIO data
  esdata:  # Volume for Elasticsearch data
