version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose NGINX on port 80 of the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the NGINX configuration file
    depends_on:
      - web-app
      - web-api

  web-app:
    build:
      context: .  # Path to your WebUI service
      dockerfile: WebUI/Dockerfile  # Ensure this is named correctly
    ports:
      - "3000:3000"  # Expose WebUI on port 3000 of the host

  web-api:
    build:
      context: .  # Path to your API service
      dockerfile: DMSystem/Dockerfile  # Ensure this is named correctly
    ports:
      - "5000:5000"  # Expose API on port 5000 of the host
